### ISSUE TITLE
There is no license, which would prohibit anyone from using this library.

### ISSUE THREAD

**Issue by AnalogFeelings** [cubicool/mbew#2]

**Comment by cubicool** [comment]
This was written as a paid gig, always with the intention of being OSS. I'm 99.9% sure it's MIT, but I'll check with with patron to make sure and then add one. Thanks. :)

**Comment by a1batross** [comment]
@cubicool any news on this? :)

**Comment by cubicool** [comment]
Sorry, I didn't notice (if you'd asked earlier). It's OSS, I'll get with
the boss and see what exactly. :)

**Comment by a1batross** [comment]
@cubicool thank you! 

As I can see, the [file](https://github.com/cubicool/mbew/blob/master/LICENSE.txt) is here now, I think this can be closed as resolved.

**Comment by cubicool** [comment]
Added LICENSE.txt file to repo.
